fun main(args : Array<String>) {
    println("Enter the Details of the student:")
    print("Enter Enrollment No.: ")
    val enrno = readLine()
    print("Enter Name: ")
    val name = readln()
    print("Enter Age: ")
    val age = readln()
    print("Enter Branch: ")
    val branch = readln()
    print("Enter Class: ")
    val classname = readln()
    print("Enter Batch: ")
    val batch = readln()
    print("Enter College Name: ")
    val collname = readln()
    print("Enter University Name: ")
    val uniname = readln()

    println("\nDetails of the student are: ")
    println("Enrollment No: $enrno")
    println("Name: $name")
    println("Age: $age")
    println("Branch: $branch")
    println("Class: $classname")
    println("Batch: $batch")
    println("College Name: $collname")
    println("University Name: $uniname")
}
